### ISSUE TITLE
backup full machine?

### ISSUE THREAD

**Issue by aulinang** [PetaByet/cdp#22]
have tried two different Servers  (different locations with Debian/ubuntu fresh install + cdp) to backup whole Linux Clients (source "/")

when i try to create a manual backup gzip stops at around 113 mb and no data gets transfered. have tried to backup 2 different Linux Clients (haphost and core i7 6gb ram ...

can anyone help me?

**Comment by PetaByet** [comment]
I'm pretty sure haphost doesn't offer 6GB RAM services? Anyway, it's likely RAM or disk space ran out, or the process is killed.

**Comment by aulinang** [comment]
I've told've tried it on 2 different servers
1x haphost
1x i7 6gb ram

The script doesnt works neither fresh debian and ubuntu
