### ISSUE TITLE
Installing curl and wget 

### ISSUE THREAD

**Issue by sentabi** [PetaByet/cdp#24]
Some 'minimal' install don't include wget and curl on default.

error after installing cdp 
```
/dev/fd/63: line 122: curl: command not found
```
how about add curl and wget on apt-get (line 43) / yum (line 63)?

**Comment by PetaByet** [comment]
The installation command requires wget or curl so I see no point in installing them using the installer.

**Comment by sentabi** [comment]
I know, I've setup cdp on my test server which don't have wget and curl both command failed, ofcourse It will failed. 

How about add to wiki, install wget or curl (or both) before doing installation. If curl already installed why I get these error message (/dev/fd/63: line 122: curl: command not found). 

I just re-install my server (debian minimalist), install wget and curl and everything goes smoothly.

**Comment by PetaByet** [comment]
Got it.
