### ISSUE TITLE
MySQL DB backup

### ISSUE THREAD

**Issue by ThomasGlass** [PetaByet/cdp#26]
When you select MySQL, I want to backup all DBs but it says I must enter at least 1DB even though it says  Leave tables empty if you want a backup of all tables.

**Comment by PetaByet** [comment]
Are the DB's owned by the same user? That's interesting.

**Comment by ThomasGlass** [comment]
Yes they are

**Comment by PetaByet** [comment]
Okay, will have a look at this soon.
