### ISSUE TITLE
Permission Denied.

### ISSUE THREAD

**Issue by kushalraha** [PetaByet/cdp#28]
can not chdir(/var/spool/clientmqueue/): Permission denied
Message could not be sent.
Mailer Error: Could not instantiate mail function.

**Comment by PetaByet** [comment]
Hello,

Please try the following commands

`chmod 770 /var/spool`
`chmod 770 /var/spool/clientmqueue`

**Comment by kushalraha** [comment]
Done that. Doesn't work.

Best,
Kushal

Sent from my iPhone on the move,please excuse my brevity.
On Wed, Apr 8, 2015 at 7:59 AM, PetaByet/cdp
<reply@reply.github.com>
wrote:Hello,

Please try the following commands

chmod 770 /var/spool
chmod 770 /var/spool/clientmqueue

—
Reply to this email directly or view it on GitHub
[https://github.com/PetaByet/cdp/issues/28#issuecomment-90784232] .[https://github.com/notifications/beacon/AEuapStCJBmpBn1ICarIXWFSnpl9ur3oks5n9IoigaJpZM4D7gLN.gif]

**Comment by PetaByet** [comment]
Try restarting sendmail.
