### ISSUE TITLE
ssh over rsa on centos not working

### ISSUE THREAD

**Issue by nitrovps** [PetaByet/cdp#29]
Apr 14 14:04:25 eu sshd[524398]: pam_unix(sshd:session): session opened for user root by (uid=0)
Apr 14 21:35:24 eu sshd[950575]: Received disconnect from 192.168.1.1: 11:

**Comment by PetaByet** [comment]
Hello,

The log entries are more than 7 hours apart.

**Comment by nitrovps** [comment]
sorted it out, ownership to apache fixed the problem



Pe 15 apr. 2015, la 01:27, PetaByet <notifications@github.com> a scris:

**Comment by kushalraha** [comment]
How did you resolve this?
