### ISSUE TITLE
I can't log me in

### ISSUE THREAD

**Issue by nghc** [PetaByet/cdp#31]
When I edit the password of an user or add a new user in user management, I am not able to log me in with this data. Even if the password and the username is right. I can't log me in. 

I get only this error: Login failed.

**Comment by PetaByet** [comment]
What is the permission of `db` folder and everything within?

**Comment by crazyindianchief** [comment]
I'm having same issue

here is db folder permissions

drwxr-xr-x.  2 root root 4096 Apr 24 04:58 .
drwxr-xr-x. 12 root root 4096 Apr 24 04:58 ..
-rwxrwxrwx.  1 root root  494 Apr 24 04:58 db-acl.json
-rwxrwxrwx.  1 root root  399 Apr 24 05:48 db-activitylog.json
-rwxrwxrwx.  1 root root    3 Apr 24 04:58 db-backupjobs.json
-rwxrwxrwx.  1 root root    3 Apr 24 04:58 db-backuplog.json
-rwxrwxrwx.  1 root root    3 Apr 24 04:58 db-backupservers.json
-rwxrwxrwx.  1 root root    3 Apr 24 04:58 db-backups.json
-rwxrwxrwx.  1 root root  132 Apr 24 05:48 db-users.json
-rw-r--r--.  1 root root   58 Apr 24 04:58 index.php

**Comment by PetaByet** [comment]
Please try manually editing `db-users.json` with a md5-encoded password.

**Comment by crazyindianchief** [comment]
login failed. 2fo is set to false and has a key btw.

**Comment by PetaByet** [comment]
Could you show me the file with the password masked?

**Comment by crazyindianchief** [comment]
sure it's a fresh install vps. I just started driving but can in about an hour. btw are there any other tutorials/guides for scheduling  prefer with cpanel. kinda a backup noob

**Comment by crazyindianchief** [comment]
[{"id":"1","username":"test","password":"098f6bcd4621d373cade4e832627b4f6","acl":"1","2fo":"false","2fokey":"IOWDGI3CUVPND6HE"}]

**Comment by PetaByet** [comment]
Please leave the `2fokey` field empty and change the password to the md5 password you want.

**Comment by crazyindianchief** [comment]
still not working
