### ISSUE TITLE
MySQL Backup not working

### ISSUE THREAD

**Issue by bradbeckett** [PetaByet/cdp#7]
Hey PetaByet, great script. After I chown -R apache:apache /var/www/html/ everything was working great. The script pulls the remote directory we specify. However we have been unable to get your CDP.me script to actually pull down MySQL (we have everything configured correctly for remote access on the other side).

It will only pull the first 339 bytes of the MySQL database:

DROP TABLE wp_yith_wcwl;

CREATE TABLE wp_yith_wcwl (  ID int(11) NOT NULL AUTO_INCREMENT,  prod_id int(11) NOT NULL,  quantity int(11) NOT NULL,  user_id int(11) NOT NULL,  dateadded timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (ID), KEY product (prod_id) ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

The e-mail report says:

Backup job (df340171bc723ec40ac5b19de0b5fc23) started Starting SQL backup MySQL query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

We are running MySQL 5.5 with cPanel on this specific test server.

Thank you.

**Comment by AppFull** [comment]
also having this
'Unable to establish a MySQL connection: Lost connection to MySQL server at 'reading initial communication packet', system error: 0'

solution?

**Comment by PetaByet** [comment]
Hello,

Would you mind trying the following command on the backup server? (replace mysql-host with the actual host)

`telnet mysql-host 3306`

**Comment by AppFull** [comment]
using IP,
telnet: Unable to connect to remote host: Connection refused

**Comment by AppFull** [comment]
working now, can connect. issue with https://mariadb.com/kb/en/mariadb/configuring-mariadb-for-remote-client-access/

another problem: the file encrypt by default, 'No Encryption' and 448b file size?

Backup job (ce**random) started
Starting SQL backup
Encrypting file with AES-256
Backup completed in 55 seconds.
Processing backup auto-delete

**Comment by PetaByet** [comment]
What do you mean?

**Comment by AppFull** [comment]
.sql backup encrypted by default even i dont chose, also its only 448bytes size
![capture-20150220-170846](https://cloud.githubusercontent.com/assets/5789170/6284513/59a55c0a-b923-11e4-9a7c-d567b8234a6e.png)

**Comment by PetaByet** [comment]
Could you please send me `db/db-backupjobs.json`?

**Comment by PetaByet** [comment]
The file you sent me doesn't seem to be the right file.

**Comment by AppFull** [comment]
wrong file, sent the correct one ;p

**Comment by PetaByet** [comment]
Okay, got it. It shouldn't encrypt the backups, would you mind providing server logins for me to check?

**Comment by AppFull** [comment]
hmm

**Comment by AppFull** [comment]
aha found the problem
1.its not working on "No Encryption" only option, **but** works if choosing encryption with password -- output shows (download encrypted) and Download (Decrypted)

2.its only working with selecting table,

Enter the MySQL database and tables to be backup (separated with a comma), eg: mydatabase table1,table2,table3. 
*Leave tables empty if you want a backup of all tables.* this not working, 
but "mydatabase table1,table2,table3" working

**Comment by PetaByet** [comment]
This is probably because you are using MariaDB.
